### ISSUE TITLE
Accept HN URL's shared from other apps.

### ISSUE THREAD

**Issue by bladecoates** [devandsev/HackerNews-Support#3]
### _This feature might be requested already, [try searching existing issues](https://github.com/devandsev/HackerNews-Support/labels/enhancement) first._
___

**Is your feature request related to a problem? Please describe.**

Allow the application to accept and recognize HN URL's from the share sheet. 

**Describe the solution you'd like**

I use a RSS reader to manage all my feeds including unread on HackerNews. It would be nice to be able to share the HN URL to the application so I can utilize the innovative comment/threading layout that your application has when reading comments. This way I can continue managing my read/unread articles in one place. In the meantime, I've been having to use your application exclusively, which leaves me sorting through what I read already on my RSS reeder app. 

**Additional context**
Would love to see the code for the comment section one day.

**Comment by devandsev** [comment]
@bladecoates You can already do that! Scroll down the share sheet, tap "Edit actions...", enable "Open in HackerNewt"
 and tap "+" sign next to it. Tap "Done" and "Open in HackerNewt" action will always be at the top. Let me know if that works for you so that I could close the issue or open a bug.

Also if you just copied the link somewhere you can tap top left button in HackerNewt on the Discover screen, it'll read the link from the pasteboard and will try to open it.


https://github.com/devandsev/HackerNews-Support/assets/17564071/75527860-61f4-4c6e-af1a-5c4bfe0ba505

**Comment by bladecoates** [comment]
Can't believe I missed that, I normally use the app icon row for sharing between apps, and the lower items for my shortcut automation! Thanks!
