### ISSUE TITLE
Bulleted lists are rendered incorrectly in comments

### ISSUE THREAD

**Issue by darsnack** [devandsev/HackerNews-Support#5]
**Describe the bug**
Bulleted lists (and quotes?) are rendered smaller in comments. See screenshot.

**To Reproduce**
Open any post that has comments with bulleted lists

**Expected behavior**
The comment is rendered with all the text as the same size.

**Device & Versions:**
 - Device: iPhone 11 Pro
 - Is the device jailbroken: no
 - iOS version: iOS 16.5.1
 - App version: 1.3.3 (1)

**Screenshots & Video**

![image](https://github.com/devandsev/HackerNews-Support/assets/4811350/b574a2c3-b7cc-4ddd-a297-fc3b3fc3bd28)

**Comment by devandsev** [comment]
Fixed in version 1.4 (1).

Fixed how code blocks are rendered.

<img src="https://github.com/devandsev/HackerNews-Support/assets/17564071/750e90ac-eb36-42b0-82f1-7da71f20d7e4" width="300">

<img src="https://github.com/devandsev/HackerNews-Support/assets/17564071/2655521d-4bd6-4f66-a279-754a860a85fa" width="300">
