### ISSUE TITLE
Allow words to be selected in normal mode for faster translations 

### ISSUE THREAD

**Issue by jasonslyvia** [devandsev/HackerNews-Support#6]
**Is your feature request related to a problem? Please describe.**
I’m a non native speaker so when I’m reading HN comments I would need to look some words up every now and then. By now I have to click the ellipse and tap “Select Text” then copy or select certain text, but I find it a bit tedious.

**Describe the solution you'd like**
Allow words to be selected in “normal mode” which there will be a popup menu including “Look Up” on iOS after long press. (not sure the behavior on Android though)

**Describe alternatives you've considered**
Maybe built in some translation functionality?

**Additional context**
As described, great app, I just tipped (a little tough), thanks for your brilliant work!

**Comment by devandsev** [comment]
@jasonslyvia Thanks, glad you like the app!

> By now I have to click the ellipse and tap “Select Text” then copy or select certain text, but I find it a bit tedious.

You can double tap the post to bring up the selection pop-up right away. Or you can go to "Settings -> Controls & behaviors" and assign the action to a long press. Then you can just double-tap the word that you need more info on to bring up the "Look Up/Translate" menu (video is attached).

Completely eliminating the intermediary selection pop-up could result in performance loss while scrolling/expanding/collapsing, because the text would be rendered via different components. But let me know if the double touch technique works for you, and if it doesn't I'll need to research more on possible solutions.

https://github.com/devandsev/HackerNews-Support/assets/17564071/6e070f01-d65f-4065-858c-3a9769108dec

**Comment by jasonslyvia** [comment]
whoa, it does mitigate the problem, I will go with that. Thanks!
